# e2image
# Autogenerated from man page /usr/share/man/man8/e2image.8.gz
complete -c e2image -s a --description 'Include file data in the image file.'
complete -c e2image -s b --description 'Get image from partition with broken primary superblock by using the superblo…'
complete -c e2image -s B --description 'Set the filesystem blocksize in bytes.'
complete -c e2image -s c --description 'Compare each block to be copied from the source  device to the corresponding …'
complete -c e2image -s f --description 'Override the read-only requirement for the source filesystem when saving the …'
complete -c e2image -s I --description 'install the metadata stored in the image file back to the device.'
complete -c e2image -s n --description 'Cause all image writes to be skipped, and instead only print the block number…'
complete -c e2image -s o --description 'Specify offset of the image to be read from the start of the source  device i…'
complete -c e2image -s O --description 'Specify offset of the image to be written from the start of the target  image…'
complete -c e2image -s p --description 'Show progress of image-file creation.'
complete -c e2image -s Q --description 'Create a QCOW2-format image file instead of a normal image file, suitable for…'
complete -c e2image -s r --description 'Create a raw image file instead of a normal image file.'
complete -c e2image -s i --description 'option to those programs.'
complete -c e2image -l sparse --description 'option to the GNU version of cp (1).'
complete -c e2image -s s --description 'Scramble directory entries and zero out unused portions of the directory bloc…'

