# mflua
# Autogenerated from man page /usr/share/man/man1/mflua.1.gz
complete -c mflua -o base --description '.'
complete -c mflua -o halt-on-error --description '.'
complete -c mflua -o ini --description '.'
complete -c mflua -o interaction --description '.'
complete -c mflua -o jobname --description '.'
complete -c mflua -o kpathsea-debug --description '.'
complete -c mflua -o output-directory --description '.'
complete -c mflua -o progname --description '.'
complete -c mflua -o recorder --description '.'
complete -c mflua -o translate-file --description '.'
complete -c mflua -o 8bit --description '.'
complete -c mflua -o help --description '.'
complete -c mflua -o version --description 'REPORTING BUGS Email bug reports to luigi. scarso@gmail. com.'

