# open
# Autogenerated from man page /usr/share/man/man1/open.1.gz
complete -c open -l help --description 'Show command synopsis.'
complete -c open -l manual --description 'Show this manual page.'
complete -c open -l version --description 'Show the xdg-utils version information.'

