# termit
# Autogenerated from man page /usr/share/man/man1/termit.1.gz
complete -c termit -s h --description '.'
complete -c termit -l help --description '.'
complete -c termit -s v --description '.'
complete -c termit -l version --description '.'
complete -c termit -s e --description '.'
complete -c termit -l execute --description '= cmd.'
complete -c termit -s i --description '.'
complete -c termit -l init --description '= file.'
complete -c termit -s n --description '.'
complete -c termit -l name --description '= name.'
complete -c termit -s c --description '.'
complete -c termit -l class --description '= class.'
complete -c termit -s r --description '.'
complete -c termit -l role --description '= role.'
complete -c termit -s T --description '.'
complete -c termit -l title --description '= title.'

