# x-terminal-emulator
# Autogenerated from man page /usr/share/man/man1/x-terminal-emulator.1.gz
complete -c x-terminal-emulator -s h --description '.'
complete -c x-terminal-emulator -l help --description '.'
complete -c x-terminal-emulator -s v --description '.'
complete -c x-terminal-emulator -l version --description '.'
complete -c x-terminal-emulator -s e --description '.'
complete -c x-terminal-emulator -l execute --description '= cmd.'
complete -c x-terminal-emulator -s i --description '.'
complete -c x-terminal-emulator -l init --description '= file.'
complete -c x-terminal-emulator -s n --description '.'
complete -c x-terminal-emulator -l name --description '= name.'
complete -c x-terminal-emulator -s c --description '.'
complete -c x-terminal-emulator -l class --description '= class.'
complete -c x-terminal-emulator -s r --description '.'
complete -c x-terminal-emulator -l role --description '= role.'
complete -c x-terminal-emulator -s T --description '.'
complete -c x-terminal-emulator -l title --description '= title.'

